name: Deploy to Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        id: build
        run: |
          echo "🚀 Starting build..."
          ../build-script.sh
          echo "::set-output name=exit-code::$?"
      - name: Deploy Project Artifacts to Vercel
        run: |
          echo "💫 Deploying project..."
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Check Build Status
        if: ${{ steps.build.outputs.exit-code == 0 }}
        run: echo "✅ Build successful"
      - name: Display Build Output
        if: ${{ steps.build.outputs.exit-code == 2 }}
        run: echo "🛑 Build canceled. Branch not allowed for Preview deployment"
