name: Deploy to Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "🛑 Build canceled. Branch not allowed for Production deployment"
            exit 1
          fi
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        id: build
        run: |
          echo "🚀 Starting build..."
          echo "::set-output name=exit-code::$?"
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          echo "💫 Deploying project..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Check Build Status
        if: ${{ steps.build.outputs.exit-code == 0 }}
        run: echo "✅ Build successful"
      - name: Display Build Output
        if: ${{ steps.build.outputs.exit-code == 2 }}
        run: echo "🛑 Build canceled. Branch not allowed for Production deployment"
