name: Develop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      docker:
        image: docker:dind
        ports:
          - 3000:3000
        options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build e rodar container Docker
      run: |
        docker build -t cypress-tests .

    - name: Executar o container com o Projeto
      run: |
        docker run --name service cypress-tests bash -c "npm start"

    - name: Ver a listagem do container
      run: |
        docker ls
    
    - name: Install Dependencies
      run: cd api && npm install

    - name: Install Cypress
      run: cd api && npx cypress install

    - name: Start application
      run: cd api && npm start &
      
    - name: Run Cypress Tests
      run: cd api && npx cypress run

    - name: Generate Report
      run: cd api && npx nyc report --reporter=text-summary

    - name: Parar e remover container Docker
      run: |
        docker stop service
        docker rm service

    - name: Upload Report
      run: cd api && npm run sonar:build