name: Develop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test with Cypress
      run: |
        docker build -t cypress-tests .
        docker run --rm -v $(pwd) cypress-tests
    
    - name: Install Dependencies
      run: cd api && npm install

    - name: Install Cypress
      run: cd api && npx cypress install

    - name: Start application
      run: cd api && npm start &
      
    - name: Run Cypress Tests
      run: cd api && npx cypress run

    - name: Generate Report
      run: cd api && npx nyc report --reporter=text-summary

    - name: Upload Report
      run: cd api && npm run sonar:build